apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uhs4kd1iq-nodejs
  janus-idp.io/tekton: uhs4kd1iq-nodejs
  backstage.io/kubernetes-id: uhs4kd1iq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uhs4kd1iq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
