apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uhs4kd1iq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:49f7419d90320c7c7a8fab9d2e0aacc6572f7abf@sha256:3b0b0394827b56a249ac5e87e661e2ff714a20ae5a7dc12fe1cd8e871532b23e
          name: container-image
